export const fakeData = [
  {
    id: 1,
    title: "Sinema 1",
    description: "Vizyondaki yeni film",
    category: "Sinema",
    date: "Sat Jun 24 2022 17:08:16 GMT+0300 (GMT+03:00)",
    city: "İstanbul",
    region: "Beşiktaş",
    map: { lat: 59.95, lng: 30.33 },
    images: [
      { id: 1, url: "/assets/cinema1.png" },
      { id: 2, url: "/assets/cinema2.png" },
      { id: 3, url: "/assets/cinema3.png" },
    ],
  },
  {
    id: 2,
    title: "Tiyatro 1",
    description: "Vizyondaki yeni tiyatro",
    category: "Tiyatro",
    date: "Sat Jun 23 2022 17:08:16 GMT+0300 (GMT+03:00)",
    city: "İstanbul",
    region: "Zeytinburnu",
    map: { lat: 59.95, lng: 30.33 },
    images: [
      { id: 1, url: "/assets/theatre.png" },
      { id: 2, url: "/assets/theatre2.png" },
      { id: 3, url: "/assets/theatre3.png" },
    ],
  },
  {
    id: 3,
    title: "Konser 1",
    description: "Vizyondaki yeni konser",
    category: "Konser",
    date: "Sat Jun 25 2022 17:08:16 GMT+0300 (GMT+03:00)",
    city: "İstanbul",
    region: "Bebek",
    map: { lat: 59.95, lng: 30.33 },
    images: [
      { id: 1, url: "/assets/concert.png" },
      { id: 2, url: "/assets/theatre2.png" },
      { id: 3, url: "/assets/theatre3.png" },
    ],
  },
  {
    id: 4,
    title: "Resim Sergisi 1",
    description: "Vizyondaki yeni resim sergisi",
    category: "Sanat",
    date: "Sat Jun 27 2022 17:08:16 GMT+0300 (GMT+03:00)",
    city: "İstanbul",
    region: "Bebek",
    map: { lat: 59.95, lng: 30.33 },
    images: [
      { id: 1, url: "/assets/concert.png" },
      { id: 2, url: "/assets/theatre2.png" },
      { id: 3, url: "/assets/theatre3.png" },
    ],
  },
  {
    id: 5,
    title: "Opera 1",
    description: "Vizyondaki yeni opera",
    category: "Sanat",
    date: "Sat Jun 28 2022 17:08:16 GMT+0300 (GMT+03:00)",
    city: "İstanbul",
    region: "Bebek",
    map: { lat: 59.95, lng: 30.33 },
    images: [
      { id: 1, url: "/assets/opera.png" },
      { id: 2, url: "/assets/opera2.png" },
      { id: 3, url: "/assets/opera3.png" },
    ],
  },
  {
    id: 6,
    title: "Festilval 1",
    description: "Vizyondaki yeni Festival",
    category: "Festival",
    date: "Sat Jul 14 2022 17:08:16 GMT+0300 (GMT+03:00)",
    city: "İstanbul",
    region: "Üsküdar",
    map: { lat: 59.95, lng: 30.33 },
    images: [
      { id: 1, url: "/assets/Festival.png" },
      { id: 2, url: "/assets/Festival2.png" },
      { id: 3, url: "/assets/Festival3.png" },
    ],
  },
  {
    id: 7,
    title: "Sinema 2",
    description: "Vizyondaki yeni film 2",
    category: "Sinema",
    date: "Sat Jun 24 2022 17:08:16 GMT+0300 (GMT+03:00)",
    city: "İstanbul",
    region: "Beşiktaş",
    map: { lat: 59.95, lng: 30.33 },
    images: [
      { id: 1, url: "/assets/cinema1.png" },
      { id: 2, url: "/assets/cinema2.png" },
      { id: 3, url: "/assets/cinema3.png" },
    ],
  },
  {
    id: 8,
    title: "Tiyatro 2",
    description: "Vizyondaki yeni tiyatro 2",
    category: "Tiyatro",
    date: "Sat Jun 23 2022 17:08:16 GMT+0300 (GMT+03:00)",
    city: "İstanbul",
    region: "Zeytinburnu",
    map: { lat: 59.95, lng: 30.33 },
    images: [
      { id: 1, url: "/assets/theatre.png" },
      { id: 2, url: "/assets/theatre2.png" },
      { id: 3, url: "/assets/theatre3.png" },
    ],
  },
  {
    id: 9,
    title: "Konser 2",
    description: "Vizyondaki yeni konser 2",
    category: "Konser",
    date: "Sat Jun 25 2022 17:08:16 GMT+0300 (GMT+03:00)",
    city: "İstanbul",
    region: "Bebek",
    map: { lat: 59.95, lng: 30.33 },
    images: [
      { id: 1, url: "/assets/concert.png" },
      { id: 2, url: "/assets/theatre2.png" },
      { id: 3, url: "/assets/theatre3.png" },
    ],
  },
  {
    id: 10,
    title: "Resim Sergisi 2",
    description: "Vizyondaki yeni resim sergisi 2",
    category: "Sanat",
    date: "Sat Jun 27 2022 17:08:16 GMT+0300 (GMT+03:00)",
    city: "İstanbul",
    region: "Bebek",
    map: { lat: 59.95, lng: 30.33 },
    images: [
      { id: 1, url: "/assets/concert.png" },
      { id: 2, url: "/assets/theatre2.png" },
      { id: 3, url: "/assets/theatre3.png" },
    ],
  },
  {
    id: 11,
    title: "Opera 2",
    description: "Vizyondaki yeni opera 2",
    category: "Sanat",
    date: "Sat Jun 28 2022 17:08:16 GMT+0300 (GMT+03:00)",
    city: "İstanbul",
    region: "Bebek",
    map: { lat: 59.95, lng: 30.33 },
    images: [
      { id: 1, url: "/assets/opera.png" },
      { id: 2, url: "/assets/opera2.png" },
      { id: 3, url: "/assets/opera3.png" },
    ],
  },
  {
    id: 12,
    title: "Festilval 2",
    description: "Vizyondaki yeni Festival 2",
    category: "Festival",
    date: "Sat Jul 27 2022 17:08:16 GMT+0300 (GMT+03:00)",
    city: "İstanbul",
    region: "Üsküdar",
    map: { lat: 59.95, lng: 30.33 },
    images: [
      { id: 1, url: "/assets/Festival.png" },
      { id: 2, url: "/assets/Festival2.png" },
      { id: 3, url: "/assets/Festival3.png" },
    ],
  },
  {
    id: 13,
    title: "Sinema 3",
    description: "Vizyondaki yeni film 3",
    category: "Sinema",
    date: "Sat Jun 15 2022 17:08:16 GMT+0300 (GMT+03:00)",
    city: "İstanbul",
    region: "Beşiktaş",
    map: { lat: 59.95, lng: 30.33 },
    images: [
      { id: 1, url: "/assets/cinema1.png" },
      { id: 2, url: "/assets/cinema2.png" },
      { id: 3, url: "/assets/cinema3.png" },
    ],
  },
  {
    id: 14,
    title: "Tiyatro 3",
    description: "Vizyondaki yeni tiyatro 3",
    category: "Tiyatro",
    date: "Sat Jun 19 2022 17:08:16 GMT+0300 (GMT+03:00)",
    city: "İstanbul",
    region: "Zeytinburnu",
    map: { lat: 59.95, lng: 30.33 },
    images: [
      { id: 1, url: "/assets/theatre.png" },
      { id: 2, url: "/assets/theatre2.png" },
      { id: 3, url: "/assets/theatre3.png" },
    ],
  },
  {
    id: 15,
    title: "Konser 3",
    description: "Vizyondaki yeni konser 3",
    category: "Konser",
    date: "Sat Jun 21 2022 17:08:16 GMT+0300 (GMT+03:00)",
    city: "İstanbul",
    region: "Bebek",
    map: { lat: 59.95, lng: 30.33 },
    images: [
      { id: 1, url: "/assets/concert.png" },
      { id: 2, url: "/assets/theatre2.png" },
      { id: 3, url: "/assets/theatre3.png" },
    ],
  },
  {
    id: 16,
    title: "Resim Sergisi 3",
    description: "Vizyondaki yeni resim sergisi 3",
    category: "Sanat",
    date: "Sat Jun 26 2022 17:08:16 GMT+0300 (GMT+03:00)",
    city: "İstanbul",
    region: "Bebek",
    map: { lat: 59.95, lng: 30.33 },
    images: [
      { id: 1, url: "/assets/concert.png" },
      { id: 2, url: "/assets/theatre2.png" },
      { id: 3, url: "/assets/theatre3.png" },
    ],
  },
  {
    id: 17,
    title: "Opera 3",
    description: "Vizyondaki yeni opera 3",
    category: "Sanat",
    date: "Sat Jun 30 2022 17:08:16 GMT+0300 (GMT+03:00)",
    city: "İstanbul",
    region: "Bebek",
    map: { lat: 59.95, lng: 30.33 },
    images: [
      { id: 1, url: "/assets/opera.png" },
      { id: 2, url: "/assets/opera2.png" },
      { id: 3, url: "/assets/opera3.png" },
    ],
  },
  {
    id: 18,
    title: "Festilval 3",
    description: "Vizyondaki yeni Festival 3",
    category: "Festival",
    date: "Sat Jul 2 2022 17:08:16 GMT+0300 (GMT+03:00)",
    city: "İstanbul",
    region: "Üsküdar",
    map: { lat: 59.95, lng: 30.33 },
    images: [
      { id: 1, url: "/assets/Festival.png" },
      { id: 2, url: "/assets/Festival2.png" },
      { id: 3, url: "/assets/Festival3.png" },
    ],
  },
];
