export const fakeData = [
  {
    id: 1,
    title: "Sinema 1",
    description: "Vizyondaki yeni film",
    category: "Sinema",
    date: "Sat Jun 24 2022 17:08:16 GMT+0300 (GMT+03:00)",
    city: "İstanbul",
    region: "İstinye",
    owner:"İstinye Park",
    map: { lat: 59.95, lng: 30.33 },
    images: [
      { id: 1, url: "/assets/cinema.png" },
      { id: 2, url: "/assets/cinema.png" },
      { id: 3, url: "/assets/cinema.png" },
    ],
  },
  {
    id: 2,
    title: "Tiyatro 1",
    description: "Vizyondaki yeni tiyatro",
    category: "Tiyatro",
    date: "Sat Jun 23 2022 17:08:16 GMT+0300 (GMT+03:00)",
    city: "İstanbul",
    region: "Beşiktaş",
    owner:"BKM",
    map: { lat: 59.95, lng: 30.33 },
    images: [
      { id: 1, url: "/assets/theatre.png" },
      { id: 2, url: "/assets/theatre.png" },
      { id: 3, url: "/assets/theatre.png" },
    ],
  },
  {
    id: 3,
    title: "Konser 1",
    description: "Vizyondaki yeni konser",
    category: "Konser",
    date: "Sat Jun 25 2022 17:08:16 GMT+0300 (GMT+03:00)",
    city: "İstanbul",
    region: "Bebek",
    owner:"Jolly",
    map: { lat: 59.95, lng: 30.33 },
    images: [
      { id: 1, url: "/assets/concert.jpg" },
      { id: 2, url: "/assets/concert.jpg" },
      { id: 3, url: "/assets/concert.jpg" },
    ],
  },
  {
    id: 4,
    title: "Resim exhibitionsi 1",
    description: "Vizyondaki yeni resim exhibitionsi",
    category: "Sanat",
    date: "Sat Jun 27 2022 17:08:16 GMT+0300 (GMT+03:00)",
    city: "İstanbul",
    region: "Galata",
    owner:"İBB",
    map: { lat: 59.95, lng: 30.33 },
    images: [
      { id: 1, url: "/assets/exhibition.jpg" },
      { id: 2, url: "/assets/exhibition.jpg" },
      { id: 3, url: "/assets/exhibition.jpg" },
    ],
  },
  {
    id: 5,
    title: "Opera 1",
    description: "Vizyondaki yeni opera",
    category: "Sanat",
    date: "Sat Jun 28 2022 17:08:16 GMT+0300 (GMT+03:00)",
    city: "İstanbul",
    region: "Taksim",
    owner:"TC Kültür Bakanlığı",
    map: { lat: 59.95, lng: 30.33 },
    images: [
      { id: 1, url: "/assets/opera.jpg" },
      { id: 2, url: "/assets/opera.jpg" },
      { id: 3, url: "/assets/opera.jpg" },
    ],
  },
  {
    id: 6,
    title: "Festilval 1",
    description: "Vizyondaki yeni Festival",
    category: "Festival",
    date: "Sat Jul 14 2022 17:08:16 GMT+0300 (GMT+03:00)",
    city: "İstanbul",
    region: "Beşiktaş",
    owner:"Bahçeşehir Üniversitesi",
    map: { lat: 59.95, lng: 30.33 },
    images: [
      { id: 1, url: "/assets/festival.jpg" },
      { id: 2, url: "/assets/festival.jpg" },
      { id: 3, url: "/assets/festival.jpg" },
    ],
  },
  {
    id: 7,
    title: "Sinema 2",
    description: "Vizyondaki yeni film 2",
    category: "Sinema",
    date: "Sat Jun 24 2022 17:08:16 GMT+0300 (GMT+03:00)",
    city: "İstanbul",
    region: "Beşiktaş",
    owner:"İBB",
    map: { lat: 59.95, lng: 30.33 },
    images: [
      { id: 1, url: "/assets/cinema.png" },
      { id: 2, url: "/assets/cinema.png" },
      { id: 3, url: "/assets/cinema.png" },
    ],
  },
  {
    id: 8,
    title: "Tiyatro 2",
    description: "Vizyondaki yeni tiyatro 2",
    category: "Tiyatro",
    date: "Sat Jun 23 2022 17:08:16 GMT+0300 (GMT+03:00)",
    city: "İstanbul",
    region: "Zeytinburnu",
    owner:"İBB",
    map: { lat: 59.95, lng: 30.33 },
    images: [
      { id: 1, url: "/assets/theatre.png" },
      { id: 2, url: "/assets/theatre.png" },
      { id: 3, url: "/assets/theatre.png" },
    ],
  },
  {
    id: 9,
    title: "Konser 2",
    description: "Vizyondaki yeni konser 2",
    category: "Konser",
    date: "Sat Jun 25 2022 17:08:16 GMT+0300 (GMT+03:00)",
    city: "İstanbul",
    region: "Bebek",
    owner:"İBB",
    map: { lat: 59.95, lng: 30.33 },
    images: [
      { id: 1, url: "/assets/concert.jpg" },
      { id: 2, url: "/assets/concert.jpg" },
      { id: 3, url: "/assets/concert.jpg" },
    ],
  },
  {
    id: 10,
    title: "Resim exhibitionsi 2",
    description: "Vizyondaki yeni resim exhibitionsi 2",
    category: "Sanat",
    date: "Sat Jun 27 2022 17:08:16 GMT+0300 (GMT+03:00)",
    city: "İstanbul",
    region: "Bebek",
    owner:"İBB",
    map: { lat: 59.95, lng: 30.33 },
    images: [
      { id: 1, url: "/assets/exhibition.jpg" },
      { id: 2, url: "/assets/exhibition.jpg" },
      { id: 3, url: "/assets/exhibition.jpg" },
    ],
  },
  {
    id: 11,
    title: "Opera 2",
    description: "Vizyondaki yeni opera 2",
    category: "Sanat",
    date: "Sat Jun 28 2022 17:08:16 GMT+0300 (GMT+03:00)",
    city: "İstanbul",
    region: "Bebek",
    owner:"İBB",
    map: { lat: 59.95, lng: 30.33 },
    images: [
      { id: 1, url: "/assets/opera.jpg" },
      { id: 2, url: "/assets/opera.jpg" },
      { id: 3, url: "/assets/opera.jpg" },
    ],
  },
  {
    id: 12,
    title: "Festilval 2",
    description: "Vizyondaki yeni Festival 2",
    category: "Festival",
    date: "Sat Jul 27 2022 17:08:16 GMT+0300 (GMT+03:00)",
    city: "İstanbul",
    region: "Üsküdar",
    owner:"İBB",
    map: { lat: 59.95, lng: 30.33 },
    images: [
      { id: 1, url: "/assets/festival.jpg" },
      { id: 2, url: "/assets/festival.jpg" },
      { id: 3, url: "/assets/festival.jpg" },
    ],
  },
  {
    id: 13,
    title: "Sinema 3",
    description: "Vizyondaki yeni film 3",
    category: "Sinema",
    date: "Sat Jun 15 2022 17:08:16 GMT+0300 (GMT+03:00)",
    city: "İstanbul",
    region: "Beşiktaş",
    owner:"İBB",
    map: { lat: 59.95, lng: 30.33 },
    images: [
      { id: 1, url: "/assets/cinema.png" },
      { id: 2, url: "/assets/cinema.png" },
      { id: 3, url: "/assets/cinema.png" },
    ],
  },
  {
    id: 14,
    title: "Tiyatro 3",
    description: "Vizyondaki yeni tiyatro 3",
    category: "Tiyatro",
    date: "Sat Jun 19 2022 17:08:16 GMT+0300 (GMT+03:00)",
    city: "İstanbul",
    region: "Zeytinburnu",
    owner:"İBB",
    map: { lat: 59.95, lng: 30.33 },
    images: [
      { id: 1, url: "/assets/theatre.png" },
      { id: 2, url: "/assets/theatre.png" },
      { id: 3, url: "/assets/theatre.png" },
    ],
  },
  {
    id: 15,
    title: "Konser 3",
    description: "Vizyondaki yeni konser 3",
    category: "Konser",
    date: "Sat Jun 21 2022 17:08:16 GMT+0300 (GMT+03:00)",
    city: "İstanbul",
    region: "Bebek",
    owner:"İBB",
    map: { lat: 59.95, lng: 30.33 },
    images: [
      { id: 1, url: "/assets/concert.jpg" },
      { id: 2, url: "/assets/concert.jpg" },
      { id: 3, url: "/assets/concert.jpg" },
    ],
  },
  {
    id: 16,
    title: "Resim exhibitionsi 3",
    description: "Vizyondaki yeni resim exhibitionsi 3",
    category: "Sanat",
    date: "Sat Jun 26 2022 17:08:16 GMT+0300 (GMT+03:00)",
    city: "İstanbul",
    region: "Bebek",
    owner:"İBB",
    map: { lat: 59.95, lng: 30.33 },
    images: [
      { id: 1, url: "/assets/exhibition.jpg" },
      { id: 2, url: "/assets/exhibition.jpg" },
      { id: 3, url: "/assets/exhibition.jpg" },
    ],
  },
  {
    id: 17,
    title: "Opera 3",
    description: "Vizyondaki yeni opera 3",
    category: "Sanat",
    date: "Sat Jun 30 2022 17:08:16 GMT+0300 (GMT+03:00)",
    city: "İstanbul",
    region: "Bebek",
    owner:"İBB",
    map: { lat: 59.95, lng: 30.33 },
    images: [
      { id: 1, url: "/assets/opera.jpg" },
      { id: 2, url: "/assets/opera.jpg" },
      { id: 3, url: "/assets/opera.jpg" },
    ],
  },
  {
    id: 18,
    title: "Festilval 3",
    description: "Vizyondaki yeni Festival 3",
    category: "Festival",
    date: "Sat Jul 2 2022 17:08:16 GMT+0300 (GMT+03:00)",
    city: "İstanbul",
    region: "Üsküdar",
    owner:"İBB",
    map: { lat: 59.95, lng: 30.33 },
    images: [
      { id: 1, url: "/assets/festival.jpg" },
      { id: 2, url: "/assets/festival.jpg" },
      { id: 3, url: "/assets/festival.jpg" },
    ],
  },
];
